### PR TITLE
Create Use-Connextra-To-Communicate-Features.md

### PR DESCRIPTION
**Pull request by jlichtinger**

### CODE REVIEW

**Comment by tperkins1** [comment]
Jon, good stuff.  Have you considered setting up daily or weekly meetings with your dev team?

**Comment by katievila** [comment]
Great work, one thing you may consider adding is talking about the pros and cons between Connextra and Job Stories.

**Comment by dvacherot** [comment]
@jlichtinger your insight is unparalleled. Should we consider adding something about how to prioritize stories (hardest frst) or how to make sure we don't build to big of a backlog (half a day/story)?

**Comment by ECohen16** [comment]
@jlichtinger fantastic work!  I especially like how you used to image to satisfy your text requirement.  Very, very clever.  Anywho, would you be amenable to adding a bit on the necessity of "confirmation" for each story, i.e., agreeing up-front upon how to determine whether the feature is successful?

**Comment by jwvirus** [comment]
:+1: :+1:

**Comment by katievila** [comment]
:+1:  :+1:

**Comment by jlichtinger** [comment]
@katievila @ECohen16 @dvacherot @tperkins1 @jwvirus  Thanks for the great suggestions! I've incorporated all of the changes, please confirm if it's good to go!

**Comment by katievila** [comment]
looks good @jlichtinger :+1:  :+1:

**Comment by ECohen16** [comment]
:+1:

**Pull request merged**
