### PR TITLE
Create howtoincentivizedevelopers.md

### PR DESCRIPTION
**Pull request by dvacherot**
This file provides some insight into the factors motivating developers and how to structure compensation

### CODE REVIEW

**Comment by dvacherot** [comment]
Welcome your comments @jlichtinger @ECohen16 @katievila @tperkins1 :smile:

**Comment by jlichtinger** [comment]
Great job Damien! You mentioned that payment through hourly prices is a good solution, but could you provide more information on the range of prices that you think are most optimal?

**Comment by katievila** [comment]
@dvacherot this looks great! One thing I would be interested in as an executive is how does this translate back to my budget?  Can you include a line that explains how my budget as an executive must have some flexibility and contingency built in? Thanks!

**Comment by dvacherot** [comment]
Thanks all. I've put in your comments. Would love thumbs up when you are ready!

**Comment by tperkins1** [comment]
This is perfect @dvacherot :+1:

**Comment by ECohen16** [comment]
:+1:

**Comment by jwvirus** [comment]
:+1: :+1:

**Pull request merged**
