### PR TITLE
how_to_use_trello_finally.md

### PR DESCRIPTION
**Pull request by jwvirus**
I highly recommend this cool product

### CODE REVIEW

**Comment by dvacherot** [comment]
@jwvirus Thanks for introducing Trello. How about adding a link to the site in your file?

**Comment by ECohen16** [comment]
Great addition @jwvirus!  Can you add a screenshot of Trello using the Image Description format?

**Comment by jwvirus** [comment]
Thanks @dvacherot @ECohen16 for your wonderful comments. Your ideas are just brilliant!!! This is the link to [link to Trello!](http://trello.com)

**Comment by jwvirus** [comment]
image

**Comment by jlichtinger** [comment]
Great work, @jwvirus! This seems like a great product. It might be helpful to discuss how you think Trello compares to other project management tools like Asana. You could even just add this link to the post: http://www.quora.com/How-does-Asana-compare-to-Trello

**Comment by katievila** [comment]
@jwvirus very cool! I need to try using the product at home too.  Do you think this product could be a useful tool for teams at work that are not working on software development?

**Comment by jwvirus** [comment]
@jlichtinger thanks for introducing Asana. I didn't know this product, but it looks cool. @katievila yes, definitely! I am already using it in another group project at school. It works! Anyways, thanks everyeon @dvacherot @ECohen16 @tperkins1 for your contributions. I think this branch is good to be submitted!

**Comment by ECohen16** [comment]
:+1:

**Comment by tperkins1** [comment]
+1

**Comment by tperkins1** [comment]
:+1:

**Comment by dvacherot** [comment]
:+1:

**Comment by jlichtinger** [comment]
:+1:

**Pull request merged**
