### PR TITLE
Create start-with-website.md

### PR DESCRIPTION
**Pull request by ECohen16**
I've added my take-aways for early-stage software development.  Let me know what you think!

@katievila @jlichtinger @dvacherot @tperkins1

### CODE REVIEW

**Comment by dvacherot** [comment]
Good job @ECohen16. I agree with your approach. Perhaps we can also mention that for large companies that have the budget it may make sense to go straight to native?

**Comment by katievila** [comment]
@ECohen16 great job!  Can you talk briefly about why for some companies (i.e. Uber) they must start with an app platform?

**Comment by ECohen16** [comment]
@dvacherot @katievila @jlichtinger great feedback!  I've incorporated your suggestions - let me know what you think.

**Comment by jwvirus** [comment]
:+1:

**Comment by dvacherot** [comment]
:+1:

**Comment by tperkins1** [comment]
Great stuff @ECohen16 :+1:

**Comment by jlichtinger** [comment]
:+1: great job, looks good to merge!

**Comment by jwvirus** [comment]
:+1: :+1:

**Pull request merged**
