### PR TITLE
Create questions_to_ask_when_hiring.md

### PR DESCRIPTION
**Pull request by katievila**

### CODE REVIEW

**Comment by tperkins1** [comment]
Great work! What don't you consider the persons fit for the company?

**Comment by jlichtinger** [comment]
Awesome work! Why don't you consider how well they explain technical information?

**Comment by dvacherot** [comment]
Thanks a lot Katie. Looks great to me. Maybe we can add something about how they keep track of the stories in the third paragraph (for instance using Trello or post-it)?

**Comment by ECohen16** [comment]
Great job @katievila!  Adding to the question of how many languages a candidate can code in, what do you think about using the "fizz buzz test" as a barometer for his or her answer?  I thought this was a handy rule of thumb to gauge coding literacy.

**Comment by jwvirus** [comment]
Wow @katievila it looks so nice! @dvacherot I'm glad you mentioned trello idea. I love trello.

**Comment by katievila** [comment]
Thanks @tperkins1, @jlichtinger, @dvacherot , @ECohen16, and @jwvirus! I loved your comments and have integrated them into the document.  Please give me a thumbs up to merge the file.

**Comment by jwvirus** [comment]
:+1 :+1

**Comment by ECohen16** [comment]
:+1:

**Comment by dvacherot** [comment]
:+1:

**Comment by jlichtinger** [comment]
:+1:

**Pull request merged**
