### PR TITLE
Create Developing_New_Software.md

### PR DESCRIPTION
**Pull request by tperkins1**
Hey guys, let me know what you think.

### CODE REVIEW

**Comment by katievila** [comment]
Great job @tperkins1, unlike @jlichtinger I really like the picture.  Could you make some additional comments in your write-up about some of the software that already exists that can be easily integrated for a new project, for example, shopify.

**Comment by dvacherot** [comment]
Thanks for this @tperkins1. Your discussion made me think of the benefit of building a "low fidelity" product to test demand. Perhaps we can include this idea somewhere.

**Comment by ECohen16** [comment]
Great job and GREAT picture of a surfer @tperkins1! To Damien's point, there are many ways to gauge demand for a product concept before investing in its development.  Can we also mention Kickstarter campaigns as an alternative?

**Comment by jwvirus** [comment]
:+1: @tperkins1 I think you've shown your keen interest in software. Good to see this.

**Comment by tperkins1** [comment]
Thanks team.  I have made the changes you guys have suggested.  I am looking for a  couple of :+1: s

**Comment by ECohen16** [comment]
got one for you right here: :+1:

**Comment by jwvirus** [comment]
:+1: :+1:

**Comment by dvacherot** [comment]
:+1:

**Pull request merged**
